- link:
    ~/.vscode/argv.json:
      path: vscode/argv.json
      if: '[ -d ~/.vscode ]' # Windows
    ~/Library/Application Support/Code/User/settings.json:
      if: '[ `uname` = Darwin ]' # macOS
      path: vscode/settings.json
    

- shell:
    - 
        if: '[ `uname` = WINDOWS_NT ]' # git bash shell 
        command: powershell.exe vscode/install.ps1
        stderr: true
        stdout: true