- link:
    ~/.vscode/argv.json:
      path: vscode/argv.json
      if: '[ -d ~/.vscode ]' # Windows
    ~/Library/Application Support/Code/User/settings.json:
      if: '[ `uname` = Darwin ]' # macOS
      path: vscode/settings.json
    

- shell:
    - 
      command: '[ -d ~/.vscode ]  && powershell.exe vscode/install.ps1'
      description: Create symlink to VSCode's settings.json for Windows.
      stderr: true
      stdout: true 